//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayOn.Model.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoSerie
    {
        public int IdVideo { get; set; }
        public int IdSerie { get; set; }
        public Nullable<int> Season { get; set; }
        public Nullable<int> Episode { get; set; }
    
        public virtual Serie Serie { get; set; }
        public virtual Video Video { get; set; }
    }
}
